--для редко изменяющихся данных
CREATE TABLESPACE TS_REST_REFERENCE
DATAFILE 'ts_rest_reference_kurs_pdb01.dbf' SIZE 100M 
AUTOEXTEND ON NEXT 50M MAXSIZE UNLIMITED;
--для данных, что часто изменяются и просматриваются
CREATE TABLESPACE TS_REST_OPERATIONAL
DATAFILE 'ts_rest_operational_kurs_pdb01.dbf' SIZE 500M 
AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED;
--исторические данные, журналы
CREATE TABLESPACE TS_REST_HISTORY
DATAFILE 'ts_rest_history_kurs_pdb01.dbf' SIZE 200M 
AUTOEXTEND ON NEXT 50M MAXSIZE UNLIMITED;
--отчеты моей тезнологии
CREATE TABLESPACE TS_REST_REPORTING
DATAFILE 'ts_rest_reporting_kurs_pdb01.dbf' SIZE 200M 
AUTOEXTEND ON NEXT 50M MAXSIZE UNLIMITED;
--индексы 
CREATE TABLESPACE TS_REST_INDEXES
DATAFILE 'ts_rest_indexes_kurs_pdb01.dbf' SIZE 200M 
AUTOEXTEND ON NEXT 50M MAXSIZE UNLIMITED;
--большие данные
CREATE TABLESPACE TS_REST_LOB
DATAFILE 'ts_rest_lob_kurs_pdb01.dbf' SIZE 100M 
AUTOEXTEND ON NEXT 50M MAXSIZE UNLIMITED;
--временное 
CREATE TEMPORARY TABLESPACE TS_REST_TEMP
TEMPFILE 'ts_rest_temp_kurs_pdb01.dbf' SIZE 200M 
AUTOEXTEND ON NEXT 50M MAXSIZE UNLIMITED;
--откат
CREATE UNDO TABLESPACE TS_REST_UNDO
DATAFILE 'ts_rest_undo_kurs_pdb01.dbf' SIZE 200M 
AUTOEXTEND ON NEXT 50M MAXSIZE UNLIMITED;

