create table restaurants (
    restaurant_id number generated by default as identity primary key,
    name nvarchar2(100) not null,
    address nvarchar2(200) not null,
    phone varchar2(20) not null,
    work_hours varchar2(100),
    unp varchar2(20)
) tablespace ts_rest_reference;

create table positions (
    position_id number generated by default as identity primary key,
    position_name nvarchar2(50) not null unique,
    default_salary number(10,2) check (default_salary >= 0)
) tablespace ts_rest_reference;

create table employees (
    employee_id number generated by default as identity primary key,
    full_name nvarchar2(100) not null,
    position_id number not null,
    restaurant_id number not null,
    salary number(10,2) not null check (salary >= 0),
    hire_date date not null,
    termination_date date,
    is_active number(1) default 1 check (is_active in (0,1)),
    training_info nvarchar2(500),
    constraint fk_employees_positions foreign key (position_id) references positions(position_id),
    constraint fk_employees_restaurants foreign key (restaurant_id) references restaurants(restaurant_id)
) tablespace ts_rest_operational;

create table shifts (
    shift_id number generated by default as identity primary key,
    employee_id number not null,
    start_time timestamp not null,
    end_time timestamp not null,
    restaurant_id number not null,
    constraint fk_shifts_employees foreign key (employee_id) references employees(employee_id),
    constraint fk_shifts_restaurants foreign key (restaurant_id) references restaurants(restaurant_id),
    constraint ch_shifts_time check (start_time < end_time)
) tablespace ts_rest_operational;

create table dish_categories (
    category_id number generated by default as identity primary key,
    category_name nvarchar2(50) not null unique
) tablespace ts_rest_reference;

create table dishes (
    dish_id number generated by default as identity primary key,
    dish_name nvarchar2(100) not null unique,
    category_id number not null,
    composition nvarchar2(500),
    weight number(5) check (weight >= 0),
    price number(10,2) not null check (price >= 0),
    popularity number default 0,
    is_available number(1) default 1 check (is_available in (0,1)),
    is_seasonal number(1) default 0 check (is_seasonal in (0,1)),
    constraint fk_dishes_category foreign key (category_id) references dish_categories(category_id)
) tablespace ts_rest_reference;

create table clients (
    client_id number generated by default as identity primary key,
    full_name nvarchar2(100) not null,
    phone varchar2(20),
    email varchar2(100) unique,
    password_hash nvarchar2(128) not null,
    birth_date date,
    registration_date date default sysdate
) tablespace ts_rest_operational;

create table reservations (
    reservation_id number generated by default as identity primary key,
    client_id number not null,
    restaurant_id number not null,
    reservation_time timestamp not null,
    guest_count number not null check (guest_count >= 1),
    status varchar2(20) default 'new' check (status in ('new','confirmed','cancelled','completed')),
    notes nvarchar2(200),
    constraint fk_reservations_client foreign key (client_id) references clients(client_id),
    constraint fk_reservations_restaurant foreign key (restaurant_id) references restaurants(restaurant_id)
) tablespace ts_rest_operational;

create table reviews (
    review_id number generated by default as identity primary key,
    client_id number not null,
    visit_date date,
    rating number(1) check (rating between 1 and 5),
    review_text nvarchar2(1000),
    review_date date default sysdate,
    status varchar2(20) default 'pending' check (status in ('pending','published','rejected')),
    employee_id number,
    handled_date date,
    constraint fk_reviews_client foreign key (client_id) references clients(client_id),
    constraint fk_reviews_employee foreign key (employee_id) references employees(employee_id)
) tablespace ts_rest_lob;

create table incidents (
    incident_id number generated by default as identity primary key,
    incident_date date default sysdate,
    description nvarchar2(1000) not null,
    resolution nvarchar2(500),
    employee_id number not null,
    constraint fk_incidents_employee foreign key (employee_id) references employees(employee_id)
) tablespace ts_rest_history;

create table orders (
    order_id number generated by default as identity primary key,
    employee_id number not null,
    client_id number,
    order_date date default sysdate,
    status varchar2(20) default 'open' check (status in ('open','in_kitchen','ready','closed')),
    notes nvarchar2(200),
    constraint fk_orders_employee foreign key (employee_id) references employees(employee_id),
    constraint fk_orders_client foreign key (client_id) references clients(client_id)
) tablespace ts_rest_operational;

create table order_items (
    order_item_id number generated by default as identity primary key,
    order_id number not null,
    dish_id number not null,
    quantity number not null check (quantity >= 1),
    price_at_moment number(10,2) not null,
    notes nvarchar2(200),
    constraint fk_orderitems_order foreign key (order_id) references orders(order_id),
    constraint fk_orderitems_dish foreign key (dish_id) references dishes(dish_id)
) tablespace ts_rest_operational;

create table checks (
    check_id number generated by default as identity primary key,
    order_id number not null unique,
    total_amount number(10,2) not null,
    discount_amount number(10,2) default 0,
    payment_method varchar2(20) check (payment_method in ('cash','card')),
    check_date date default sysdate,
    employee_id number not null,
    constraint fk_checks_order foreign key (order_id) references orders(order_id),
    constraint fk_checks_employee foreign key (employee_id) references employees(employee_id)
) tablespace ts_rest_operational;

create table financial_reports (
    report_id number generated by default as identity primary key,
    restaurant_id number not null,
    report_period_start date not null,
    report_period_end date not null,
    generation_date date default sysdate,
    report_type varchar2(20) check (report_type in ('sales','popularity','staff')),
    constraint fk_financial_reports_restaurant foreign key (restaurant_id) references restaurants(restaurant_id)
) tablespace ts_rest_reporting;

select * from restaurants;
select * from positions;
select * from employees;
select * from shifts;
select * from dish_categories;
select * from dishes;
select * from clients;
select * from reservations;
select * from reviews;
select * from incidents;
select * from orders;
select * from order_items;
select * from checks;
select * from financial_reports;
